### ISSUE TITLE
[UX]Need to support Launch Configs (or some other way to quickly launch last launched experiment

### ISSUE THREAD

**Issue by 32kda** [musket-ml/ds-ide#1]
Imagine the following scenario
1. You configure experiment (module, config.yaml, etc.)
2. You start experiment
3. Due to some mistake, it fails
4. You correct mistake and need to re-launch exatly the same experiment again

No way to easily do it. Eclipse user would just try hitting F11 (lauch last launched), which wouldn't do what he expect.
Another issue is that even our experiment Launch Settings dialog does not persist last entered values.

**Comment by petrochenko-pavel-a** [comment]
This seems to be done!
